name = "site-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 定时任务配置 - 每2个小时运行一次
[triggers]
crons = ["0 */2 * * *"]

# KV 存储配置
[[kv_namespaces]]
binding = "SITEMAP_STORAGE"
id = "5882299032c94347b203265682d861f7"
preview_id = "2e0377dc755c417bb08b2a7b1f77630e"

# 环境变量
[vars]
NODE_ENV = "production"

# 生产环境配置
[env.production]
name = "site-bot-prod"

# 开发环境配置
[env.staging]
name = "site-bot-staging" 